### ISSUE TITLE
Make a frequency allocation chart

### ISSUE THREAD

**Issue by jrmlhermitte** [EarthFrequencies/earth-frequencies-webui#11]
# Description
It would be nice to visually demonstrate the frequency allocations.

A good starting point might be to create a frequency allocation chart as this one [here](https://www.ntia.doc.gov/files/ntia/publications/january_2016_spectrum_wall_chart.pdf) for US allocations.

This could be tackled in a few steps:
## 1. Use mock data
Setup some mock data. Don't worry about a format yet or coupling your plot with how data is currently saved. Just worry about what you need for plotting.

For example, I'd suggest creating this:
```javascript
{allocations:
  [
    {band: {lowerFrequency: 90000, upperFrequency: 110000}, name: "Radio Navigation"},
    {band: {lowerFrequency: 1705000, upperFrequency: 1800000, name: "Fixed"},
    {band: {lowerFrequency: 1705000, upperFrequency: 1800000, name: "Mobile"},
    {band: {lowerFrequency: 540000000, upperFrequency: 720000000, name: "Television"}
  ]
}
```
where the frequency are in Hz. The above should probably enough.
Make sure to capture edge cases, like overlapping frequencies.

## 2. Plot the Allocations
Once you have some good mock data, use it to generate a test chart. This is really up to you. If anyone has suggestions please add them to this issue.

## 3. Connect to the actual data
Look at the latest version of this repo and check to see how the frequencies data is loaded.
This is currently changing very rapidly. If you think the data format should be changed in anyway, suggestions are welcome.

## 4. Finishing touches
We should make additional issues for finishing touches for someone else to eventually complete.
Here are some we should add:
- labels
- labels change units depending on the magnitude (ex: use kHz or MHz depending on how big the numbers are)
- hover links allow users to see descriptions
- add a color legend for types like [here](https://www.ntia.doc.gov/files/ntia/publications/january_2016_spectrum_wall_chart.pdf). this will require two issues: one to update the data with a category field if needed and one to add the legend
- anything else?

# Example
Frequency allocations should look sometihng like this (but more visually appealing suggesitons welcome)
![Screenshot from 2021-12-14 16-21-58](https://user-images.githubusercontent.com/705366/146081394-05140191-2baa-4bb4-9c24-2685b9c3cf7f.png)

**Comment by ajmas** [comment]
We can use a similar design as in the following page: http://www.classic.grss-ieee.org/frequency_allocations.html

So an initial version could even use divs, where the width is fixed. For example:

```html
<div class="freq-chart">
  <div class="freq-range" title="200MHz-300MHz">
    <div class="freq-allocation">label</label>
  </div>
</div>
```

```
const allocationByRange: Record<string, any> = {};
allAllocations.forEach(allocation => { 
  // see if a key exists in allocationByRange
  // if it does not create an entry, with key being `${lowerRange}-${upperRange}` and value an empty array
  // push allocation into array the key points to 
}
const keys = Object.keys(allocationByRange);
return keys.map(key => ({
    lowerFrequency: allocationByRange[key][0].lowerFrequency,
    upperFrequency: allocationByRange[key][0].upperFrequency,
    allocations: allocationByRange[key]
}));
```

**Comment by jrmlhermitte** [comment]
this is great. ill include a screen of your link just in case. (I prefer to avoid clicking links when possible. Also in mobile mode this doesn't show up well)
![Screenshot from 2021-12-15 16-59-43](https://user-images.githubusercontent.com/705366/146271746-6031c569-df96-4f23-b12e-8f1484f27216.png)

This is perfect. All we need is the allocationbyrange data structure. For example, [here](https://github.com/EarthFrequencies/earth-frequencies-data/blob/main/data/allocation-tables/us/non-government/allocations.txt#L21), FIXED spands a slightly larger range than maritime mobile.
I will update the converter to do this. I think it makes sense for the converter to validate and convert the data into this format. But we could move the logic to the viewer side if we prefer.
