### ISSUE TITLE
Create frequency browsing component

### ISSUE THREAD

**Issue by ajmas** [EarthFrequencies/earth-frequencies-webui#3]
Create a component to browse and select the frequency range to display.

The model value should be in the form of a range object:

```json
{
  "lowerFrequrency": 0,
  "upperFrequency": 0
}
```

**Comment by jrmlhermitte** [comment]
Models are partly propose [here](https://github.com/EarthFrequencies/earth-frequencies-webui/pull/8/files#diff-2c93998df53ed2143f77ed8c59ceee5871578e9e08e500eadf3d0c6c43028276R1) when creating the allocations table component:
```typescript
class FrequencyRange {
  lowerFrequency: number
  upperFrequency: number
  constructor (lowerFrequency: number, upperFrequency: number) {
    this.lowerFrequency = lowerFrequency;
    this.upperFrequency = upperFrequency;
  }
}
```

We could possibly just use that.

I propose we first get the table reading from mock data (#8), then work on this filter component just after. What do you think?

**Comment by ajmas** [comment]
This is now implemented
